# SQLite version 3.x
#   gem install sqlite3
development:
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  #adapter: mysql
  #host: 10.0.2.4
  #username: hackathon
  #password: doubanhulu
  #database: weibo_diary

